---
- name: Obtain IP address from server
  hosts: localhost 
  tasks: 
    name: Obtaining IP
    command: "openstack server list --os-cloud=8ff4-project | grep -i appdb1 | awk '{print $8}'| awk -F= '{print $2}'"
    register: command_output  

- name: Deploy, configure, and populate Postgres 12
  hosts: database_servers
  become: true
  gather_facts: true
  collections:
    - community.postgresql
  tags:
    - database_servers

  roles:
  
    - postgres

- name: Deploy, configure, and populate flask repo and virtualenv
  hosts: app_servers
  become: true
  gather_facts: true
  tags:
    - app_servers

  roles:

    - flask
    
- name: Deploy haproxy load balancer
  hosts: load_balancers
  gather_facts: false 
  become: true

  tags:
    - load_balancers

  roles:

    - haproxy

...    
