---
- name: Deploy, configure, and populate Postgres 12
  hosts: database_servers:app_servers:load_balancers
  become: true
  gather_facts: true
  collections:
    - community.postgresql
  tags:
    - database_servers
  roles:
    - postgres
  when: inventory_hostname in database_servers

  tags:
    - app_servers
  roles:
    - flask
  when: inventory_hostname in app_servers
  tags:
    - load_balancers
  roles:
    - haproxy
  when: inventory_hostname in load_balancers
...    
