---
- name: Deploy, configure, and populate Postgres 12
  hosts: database_servers
  become: true
  gather_facts: true
  collections:
    - community.postgresql
  tags:
    - database_servers
  roles:
    - postgres
  - name: get IP address appdb1
    debug: hostvars['appdb1']['ansible_default_ipv4']['address']
    register: ip_addr_db1

- name: Deploy, configure, and populate flask repo and virtualenv
  hosts: app_servers
  become: true
  gather_facts: true
  tags:
    - app_servers

  roles:

    - flask
    
- name: Deploy haproxy load balancer
  hosts: load_balancers
  gather_facts: false 
  become: true

  tags:
    - load_balancers

  roles:

    - haproxy

...    
