---

- name: Deploy, configure, and populate Postgres 12
  hosts: database_servers
  become: true
  gather_facts: false
  collections:
    - community.postgresql
  tags:
    - database_servers
  roles:
    - postgres

- name: Deploy, configure, and populate flask repo and virtualenv
  hosts: app_servers:database_servers
  become: true
  gather_facts: true
  tags:
    - application_servers
  roles:
    - flask
  when: inventory_hostname in '{{ app_servers }}'
    
- name: Deploy haproxy load balancer
  hosts: load_balancers
  gather_facts: false 
  become: true
  tags:
    - load_balancers

  roles:
    - haproxy

...    
